packages:
  - "./"
allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true
saveExact: true
minimumReleaseAge: 10080
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - pnpm
  - "@pnpm/exe.*"
update:
  githubActions: true
