name: Cloudflare Pages

on:
  schedule:
    # 毎週月曜日の0時0分
    - cron: "0 0 * * 1"

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: nuxt generate
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: newt239.dev
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
