name: Typecheck & Linting
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup dependencies
        run: bun install
      - name: Build packages
        run: bun run build
      - name: TypeScript Compile Check
        run: bun tsc --noEmit
      - name: Run ESLint
        run: bun run lint
